sonar.projectKey=gokulggowda-bits_aceest-fitness-devops
sonar.organization=gokulggowda-bits
sonar.projectName=ACEest Fitness
sonar.projectVersion=2.0
sonar.sources=.
sonar.language=py
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.exclusions=venv/**,tests/**,__pycache__/**,.github/**,k8s/**,node_modules/**